# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c794fd7c9e17d6c32de85b9baef8b26019b68257fc4795d0ec48f248cb66bda60441732c6aec8dfa428b39293af734ebd1a6c4d27bcf8c8a50781846f67e1d2e

test:
  secret_key_base: 4d2f235ddfdecce5abaa913059fa7b0f1cc27fe59e39b1deda9e5d09c6eada7bda60397147f0a49af503df33d4f54bff06e59cf6a9e45268db6496b642a7de10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
